# Generated by Django 5.2.1 on 2025-05-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HECMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date these settings take effect')),
                ('fha_lending_limit', models.DecimalField(decimal_places=2, help_text='Maximum FHA lending limit', max_digits=12)),
                ('min_age', models.IntegerField(default=62, help_text='Minimum age to qualify for HECM')),
                ('mip_rate', models.DecimalField(decimal_places=4, default=0.02, help_text='Mortgage Insurance Premium rate', max_digits=5)),
                ('origination_fee_min', models.DecimalField(decimal_places=2, default=2500, help_text='Minimum origination fee', max_digits=8)),
                ('origination_fee_cap', models.DecimalField(decimal_places=2, default=6000, help_text='Maximum origination fee', max_digits=8)),
                ('first_tier_limit', models.DecimalField(decimal_places=2, default=200000, help_text='Limit for first tier origination fee calculation', max_digits=12)),
                ('first_tier_rate', models.DecimalField(decimal_places=4, default=0.02, help_text='Rate for first tier origination fee calculation', max_digits=5)),
                ('second_tier_rate', models.DecimalField(decimal_places=4, default=0.01, help_text='Rate for second tier origination fee calculation', max_digits=5)),
            ],
            options={
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='HECMInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_value', models.DecimalField(decimal_places=2, help_text='Value of the home in dollars', max_digits=12)),
                ('age', models.IntegerField(help_text='Age of the youngest borrower or eligible non-borrowing spouse')),
                ('interest_rate', models.DecimalField(decimal_places=3, help_text='Expected interest rate (annual)', max_digits=5)),
                ('existing_mortgage', models.DecimalField(decimal_places=2, help_text='Amount needed to pay off existing mortgage', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='HECMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_limit_factor', models.DecimalField(decimal_places=5, max_digits=6)),
                ('principal_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origination_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mortgage_insurance_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_closing_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_closing_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_cash_out', models.DecimalField(decimal_places=2, max_digits=12)),
                ('config_used', models.ForeignKey(help_text='Configuration used for this calculation', on_delete=django.db.models.deletion.PROTECT, to='myhecmapp.hecmconfig')),
                ('input_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='myhecmapp.hecminput')),
            ],
        ),
        migrations.CreateModel(
            name='PLFTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Age of youngest borrower')),
                ('interest_rate', models.DecimalField(decimal_places=3, help_text='Expected interest rate', max_digits=5)),
                ('factor', models.DecimalField(decimal_places=5, help_text='Principal Limit Factor', max_digits=6)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plf_entries', to='myhecmapp.hecmconfig')),
            ],
            options={
                'unique_together': {('config', 'age', 'interest_rate')},
            },
        ),
    ]
